src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(
     *     message = "Votre email est pas valide",
     *     checkMX = true
     * )
     * @Assert\NotBlank()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $avatar;

    public function getId()
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use \Symfony\Component\HttpFoundation\Request;
use \Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Entity\Email;
use App\Entity\Category;
use App\Form\EmailType;
use App\Entity\Contact;
use App\Form\CategoryType;
use App\Form\ContactType;
use \Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/mail")
 */
class MainController extends Controller
{
    /**
     * @Route("/inbox", name="main")
     */
    public function inbox(Request $request)
    {
        $mails = $this->getDoctrine()
        ->getRepository(Email::class)
        ->findAll();

        $categorys = $this->getAllCategory();

        $defaultData = array('message' => 'Type your message here');

        $search_bar = $this->searchBarForm($defaultData);

        $search_bar->handleRequest($request);

        if ($search_bar->isSubmitted() && $search_bar->isValid()) {

            $search_value = htmlspecialchars($search_bar->getData()['search']);
            $filtre = htmlspecialchars($search_bar->getData()['Trier']);
            $search_value_string = 'Searching for "'. $search_value .'"';

            $mails = $this->getDoctrine()
            ->getRepository(Email::class)
            ->findByFilter($search_value,$filtre);

            return $this->render('main/category.html.twig', [
                'mails' => $mails,
                'category' => $search_value_string,
                'categorys' => $categorys
            ]);

        }


        return $this->render('main/index.html.twig', [
            'mails' => $mails,
            'search_bar' => $search_bar->createView(),
            'categorys' => $categorys
        ]);
    }

    /**
     * @Route("/inbox/{id}", name="byId", requirements={"id":"\d+"})
     */
    public function byId($id, Request $request)
    {
        $em = $this->getDoctrine()
                   ->getManager();
        $mail = $em->getRepository(Email::class)
                   ->find($id);
        $categorys = $this->getAllCategory();

        $array_categories;
        foreach($categorys as $category){
            $array_categories[$category->getName()] = $category->getName();
        }

        //Form Lié à aucune entité mais nécéssaire pour sélectionné les différentes catégories
       $defaultData = array('message' => 'Type your message here');
       $form = $this->createFormBuilder($defaultData)
                    ->add('Categorie', ChoiceType::class, array(
                            'label' => '',
                            'choices'  => $array_categories
                    ))
                    ->add('save', SubmitType::class, array('label' => 'Ajouter une catégorie'))
                    ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //Séléction du champ
            $data = $form->getData()["Categorie"];
            //Récupération via une requête SQL D'une catégorie par rapport au champ récupéré
            $category = $this->getDoctrine()
                        ->getManager()
                        ->getRepository(Category::class)
                        ->findByCategoryName($data);
            //Assignation à l'email en question de la catégorie dont il dépend via une Instance de Catégorie
            $mail->setCategory($category);
            $em->flush();

            return $this->redirectToRoute('main');
        }


        return $this->render('main/mail.html.twig', [
            'mail' => $mail,
            'form' => $form->createView(),
            'categorys' => $categorys
        ]);
    }


    /**
     * @Route("/new", name="newMail")
     */
    public function new(Request $request){
        $contacts = $this->getDoctrine()
        ->getRepository(Contact::class)
        ->findAll();

        $email = new Email();

        $form = $this->createForm(EmailType::class, $email)
            ->add('save', SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $email = $form->getData();
                foreach($contacts as $contact){
                    if($contact->getEmail() === $email->getRecipient()){
                        $em = $this->getDoctrine()->getManager();
                        $em->persist($email);
                        $em->flush();

                        return $this->redirectToRoute('main');
                    }
                    else{
                        $error = "L'adresse que vous avez validée ne fait pas parti de votre agenda de contact, veuillez lier un contact à cette addresse mail pour l'utiliser";
                    }
                }
        }

        $categorys = $this->getAllCategory();

        return $this->render('main/form.html.twig', [
            'form' => $form->createView(),
            'categorys' => $categorys,
            'error' => $error = isset($error) ? $error: ''
        ]);
    }

    /**
     * @Route("/category/new", name="newCategory")
     */
    public function newCategory(Request $request){

        $category = new Category();

        $form = $this->createForm(CategoryType::class, $category)
            ->add('save', SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $category = $form->getData();
                $em = $this->getDoctrine()->getManager();
                $em->persist($category);
                $em->flush();

                return $this->redirectToRoute('main');

        }

        $categorys = $this->getAllCategory();

        return $this->render('main/form_cat.html.twig', [
            'form' => $form->createView(),
            'categorys' => $categorys
        ]);
    }

    /**
     * @Route("/category/{param}", name="byCategory")
     */
    public function filterByCategory($param){
        $mails = $this->getDoctrine()
        ->getRepository(Email::class)
        ->byCategory($param);

        $categorys = $this->getAllCategory();

        return $this->render('main/category.html.twig', [
            'mails' => $mails,
            'categorys' => $categorys,
            'category' => $param
        ]);
    }

    /**
     * @Route("/contact/new", name="newContact")
     */
    public function newContact(Request $request){

        $contact = new Contact();

        $form = $this->createForm(ContactType::class, $contact)
            ->add('save', SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contact = $form->getData();
                $em = $this->getDoctrine()->getManager();
                $em->persist($contact);
                $em->flush();

                return $this->redirectToRoute('contact');

        }

        $categorys = $this->getAllCategory();

        return $this->render('main/form_contact.html.twig', [
            'form' => $form->createView(),
            'categorys' => $categorys
        ]);
    }

    /**
     * @Route("/contact", name="contact")
     */
    public function AllContact(){
        $contacts = $this->getDoctrine()
        ->getRepository(Contact::class)
        ->findAll();

        $categorys = $this->getAllCategory();


        return $this->render('main/contact.html.twig', [
            'contacts' => $contacts,
            'categorys' => $categorys
        ]);
    }

    /**
     * @Route("/contact/edit/{id}", name="editContact")
     */
    public function editContact($id, Request $request){
        $em = $this->getDoctrine()->getManager();
        $contact = $em->getRepository(Contact::class)->find($id);

        $form = $this->createForm(ContactType::class, $contact)
        ->add('save', SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            return $this->redirectToRoute('contact');
        }

        $categorys = $this->getAllCategory();

        return $this->render('main/form_contact.html.twig', array(
            'form' => $form->createView(),
            'categorys' => $categorys
        ));

    }

    /**
     * @Route("/contact/delete/{id}", name="deleteContact")
     */
    public function deleteContact($id){
        $em = $this->getDoctrine()->getManager();
        $contact = $em->getRepository(Contact::class)->find($id);

        $em->remove($contact);
        $em->flush();

        return $this->redirectToRoute('contact');
    }

    //REQUETE AJAX POUR RECUPERER LE TABLEAU DE CONTACT POUR LA CONCATÉNATION
    /**
     * @Route("/contact/getAll", name="GetAll")
     */
    public function getAll(){
        $contacts = $this->getDoctrine()
        ->getRepository(Contact::class)
        ->findAll();
        $datas;
        foreach($contacts as $contact){
            $datas[] = $contact->getEmail();
        }
        return $response = new JsonResponse($datas);
    }

    public function getAllCategory(){
        return $this->getDoctrine()
        ->getRepository(Category::class)
        ->findAll();
    }

    public function searchBarForm($defaultData){

        return $this->createFormBuilder($defaultData)
                 ->add('search', TextType::class)
                 ->add('Trier', ChoiceType::class, array(
                         'label' => '',
                         'choices'  => array(
                             'Par sujet' => 'subject',
                             'Par Message' => 'message'
                        )
                    ))
                 ->add('save', SubmitType::class, array('label' => 'Chercher un mail avec ces paramètres'))
                 ->getForm();
    }

}

templates/main/category.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<div class="box"></div>
    <h1> {{ category }}</h1>
    <div class="mails">
    {% for mail in mails %}
    <a href="{{ path('byId', {id : mail.id}) }}">
    <div class="mail">
        <div class="sender">{{ mail.sender }}</div>
        <div class="recipient">{{ mail.recipient }}</div>
        <div class="subject">{{ mail.subject }}</div>-
        <div class="message">{{ mail.message }}</div>
    </div>
    </a>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/main/contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<div class="box"></div>
    <a href="{{ path('newContact')}}">New Contact</a><br>
    <h1>Vos contacts</h1>
    {% for contact in contacts %}
        <div class="contact_div">
        <img class="contact_img" src="{{ asset(contact.avatar) }}">
        <div class="name">
            <div>{{ contact.firstName }}</div>
            <div>{{ contact.lastName }}</div>
        </div>
        {{ contact.email }}
        <div class="crud">
            <a href="{{ path('editContact',{id : contact.id})}}">Edit</a>
            <a href="{{ path('deleteContact',{id : contact.id})}}">Delete</a>
        </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/main/error.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% endblock %}

templates/main/form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<div class="box"></div>
    <div class="form_container">
        {{ form_start(form) }}
        <div class="contact_label">Sender</div>
        {{ form_widget(form.sender)}}
        <div class="contact_label">Recipient</div>
        {{ form_widget(form.recipient , { 'attr': {'class': 'auto'} })  }}
        {{ error }}
        <div class="autocompletion_item"></div>
        <div class="contact_label">Subject</div>
        {{ form_widget(form.subject)}}
        <div class="contact_label">Message</div>
        {{ form_widget(form.message , { 'attr': {'class': 'textrea'} })}}
        {{ form_widget(form.save, { 'attr': {'class': 'add_button_category'} }) }}

        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/main/form_cat.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<div class="box"></div>
    <h1>New Category</h1>
    {{ form_start(form) }}
    Nom de la nouvelle catégorie :<br>
    {{ form_widget(form.name) }}
    {{ form_widget(form.save , { 'attr': {'class': 'add_button_category'} }) }}
    {{ form_end(form) }}
</div>
{% endblock %}

templates/main/form_contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<div class="box"></div>
    <h1>New Contact</h1>
    <div class="form_container">
        {{ form_start(form) }}
        <div class="contact_label">Prénom</div>
        {{ form_widget(form.first_name) }}
        <div class="contact_label">Nom</div>
        {{ form_widget(form.last_name) }}
        <div class="contact_label">Email</div>
        {{ form_widget(form.email) }}
        <div class="contact_label">Lien de l'image</div>
        {{ form_widget(form.avatar) }}
        {{ form_widget(form.save, { 'attr': {'class': 'add_button_category'} }) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<div class="box">
    <div class="search_bar">
    {{ form_start(search_bar) }}
    {{ form_widget(search_bar.search) }}
    {{ form_widget(search_bar.Trier) }}
    {{ form_widget(search_bar.save,  { 'attr': {'class': 'add_button_category'} }) }}
    {{ form_end(search_bar) }}
    </div>
</div>
    <div class="mails">
    {% for mail in mails %}
    <a href="{{ path('byId', {id : mail.id}) }}">
    <div class="mail">
        <div class="sender">{{ mail.sender }}</div>
        <div class="recipient">{{ mail.recipient }}</div>
        <div class="subject">{{ mail.subject }}</div>-
        <div class="message">{{ mail.message }}</div>
    </div>
    </a>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/main/mail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<div class="box"> </div>
        <div class="individual_mail">
                <h1 class="individual_subject">{{ mail.subject }}</h1>
                <hr>
                <div class="individual_sender"><b>{{ mail.sender }}</b></div>
                <div class="individual_recipient">to {{ mail.recipient }}</div>
                <div class="individual_message">{{ mail.message }}</div>
                <div class="individual_form">{{ form_start(form) }}
                <div>
                        {{ form_widget(form.Categorie) }}
                        {{ form_widget(form.save , { 'attr': {'class': 'add_button_category'} })  }}
                </div>
                {{ form_end(form) }}</div>
        </div>
</div>
{% endblock %}